name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest TryHackMe image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rossplennon/tryhackme-badge-workflow@main
        with:
          # Replace with your TryHackMe username
          username: "rossplennon"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
